### ISSUE TITLE
navigate() returns TypeError when using RegExp as route path

### ISSUE THREAD

**Issue by mritzerfeld** [krasimir/navigo#270]
I've been using Navigo for quite some time in a custom React wrapper. Until now, using RegExp as route path instead of strings worked perfectly. After upgrading from 7.1.2 to 8.8.0 this week, Navigo.navigate() however sometimes throws a TypeError exception

`TypeError: t.replace is not a function. (In 't.replace(/\/+$/,"")', 't.replace' is undefined)`

This happens, when a RegExp is provided to matchLocation() as first argument and this value is run through clean() function, which expects a String. Since replace() isn't available on RegExp objects, the above exception is thrown.

Enclosing the same RegExp routes definitions in strings works without any problem.

It would also be great, if capture groups in RegExp route definitions would be evaluated and added to Match.data object.

**Comment by krasimir** [comment]
Hey @mathiasrw,

it seems like a bug. Can you post the exact code that you are using.

**Comment by lBeJIuk** [comment]
Hi. I have encountered a similar problem.
The problem is probably caused by "checkForLeaveHook.ts" line 21.
I made a fork and added an example in it.
But unfortunately I don't know how to refer to that commit correctly.

**Comment by mritzerfeld** [comment]
The leave hook was indeed the missing piece. I had setup a test environment which worked fine, but without the hook, which is used in our React wrapper.

The follwing example reproduces the bug.
```
import Navigo from 'navigo';

const test = new Navigo();

test.on(/xyz\/[0-9a-z]{4,8}$/, () => console.log('route called'), {
    leave: (done, match) => {
        done();
    }
});

test.on(/xyz\/[0-9a-z]{4,8}\/sub$/, () => console.log('route 2 called'), {
    leave: (done, match) => {
        done();
    }
});

test.navigate('/xyz/asdf');
test.navigate('/xyz/asdf/sub');
```

**Comment by krasimir** [comment]
Thanks. I'll invetstigate.

**Comment by krasimir** [comment]
@mritzerfeld @lBeJIuk should be fixed now. Please try with `8.8.1` version.

**Comment by mritzerfeld** [comment]
@krasimir 
Thanks a lot. This fixes the TypeError.

However it seems like capture groups are completely removed from the RegExp when adding a route, as shown of an adapted version of my above example:

```
test.on(/xyz\/(?<name>[0-9a-z]{4,8})$/, (match) => console.log('route called', match.route.path), {
    leave: (done, match) => {
        done();
    }
});
```

Our custom Route component in React reads those capture groups when RegExp paths are used and communicates them to child components. This worked perfectly in v7.

**Comment by krasimir** [comment]
The capture groups are passed into the `data` prop. For example:

```js
router.on(/xyz\/([0-9a-z]{4,8})\/(sub)$/, (match) => {
  console.log(match.data); // ["asdf", "sub"]
});
router.("/xyz/asdf/sub");
```

**Comment by mritzerfeld** [comment]
I'm aware of the data array. What I am going for are named groups, which should create an object in match.data like Navigo's regular string path parameters. Those name declarations, as used in my previous post, are completely removed when the route is added.

**Comment by krasimir** [comment]
I see. Can you try the new `8.8.4` version. The `data` object now should contain what you expect.

**Comment by mritzerfeld** [comment]
We're almost there. I checked the new release and it works with your example, but with none of production apps. I still end up with match.data being an array.

This last issue is caused by line 106 of utils.ts

```
const regexp = new RegExp(pattern, MATCH_REGEXP_FLAGS);
```

If pattern already is a RegExp, this results in match.groups being undefined, thus returning the array. If this line is changed as following, it works like a charm:

```
const regexp = pattern instanceof RegExp ? pattern : new RegExp(pattern, MATCH_REGEXP_FLAGS);
```

Many thanks for your great work!

**Comment by krasimir** [comment]
Hm ... there is such check earlier in the code. Can you post a snippet that illustrates the failure.

**Comment by mritzerfeld** [comment]
Unfortunately not. I used the very same code from your example with console.log() instead of the render helper and called the route with router.resolve(). The project uses webpack, but standalone or CDN versions didn't work either. Only the above change worked to get the parameters as object.

**Comment by krasimir** [comment]
Hm... interesting. Do check how your transpiled code looks like. I had a problem with babel and couldn’t transpile properly the named groups.

Best regards

**Comment by mritzerfeld** [comment]
It seems indeed to be a problem with babel which I'll have to investigate further.
